version: '3.9'

services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    volumes:
      - .docker/mailhog:/data
    ports:
      - "1025:1025"
      - "8025:8025"
  bucket:
    container_name: bucket
    image: minio/minio
    volumes:
      - .docker/bucket:/data
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
  api: 
    build: .
    container_name: api
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
